### PR TITLE
flw separate package

### PR DESCRIPTION
**Pull request by pmazzini**
Create separate flw package. This is the first step towards #29.

### CODE REVIEW

**Comment by jeffbean** [comment]
the problem is this is all breaking changes. 

If we want to do this, we need to start a v2 branch.

**Comment by jeffbean** [comment]
Overall - we may want to talk through how we want to start working on or queueing up all the breaking changes, and get a v2 branch going. 

We could do something here where we cut a final 1.X release as master today, and start making breaks in a branch. I would like to maintain master be non-breaking, but maintaining a 1.X branch may be fine for this lib, as changes are not frequent.

**Comment by pmazzini** [comment]
I would keep master for active development.

**Comment by jeffbean** [comment]
> I would keep master for active development.

if this is the case, im OK with that, but we need to cut a final 1.X, any breaking changes beyond that I can backport as needed off of that final cut. I can cut a release now, we need the Reconfig APIs I added that are not in the latest tagged release.

**Comment by jeffbean** [comment]
> > I would keep master for active development.
> 
> if this is the case, im OK with that, but we need to cut a final 1.X, any breaking changes beyond that I can backport as needed off of that final cut. I can cut a release now, we need the Reconfig APIs I added that are not in the latest tagged release.

https://github.com/go-zookeeper/zk/releases/tag/v1.0.2 

let me know if we want more details or anything specific on the release, ill promote it EOD or tomorrow if no there is no objection.

**Comment by pmazzini** [comment]
Looks ok to me. Thanks.

**Comment by jeffbean** [comment]
> I would keep master for active development.

Coming back to this, would you be open to having active development on a `dev` branch, allowing us to keep master green and in line with the latest major release? This would allow us to cherry-pick non breaking changes over to master. This also allows high levels of breaking changes in the dev branch, and would prevent any consumers that use master in their go dep system from reaching out about any churn we may be causing. 

In the end, when we want to cut v2, its a merge from dev -> master, and then master still remains in line with the latest major release.

**Comment by pmazzini** [comment]
I think that would be overcomplicating things. Development has not been active in the last months to make it worth to maintain different branches.

I would keep master for current development instead of having to do a merge from another branch onto master for future releases.

Users of the library can use go mod to stick to a certain commit or release.

Anyway, I am open to hearing other opinions @nemith  @yarikk

**Comment by yarikk** [comment]
Every PR is a branch of a sort, active development happens there, and we merge one when we feel confident enough about them.  Until we see an unmanageable influx of poorly tested changes (I hope we not) having a lagging master will just raise the administrative toll unnecessarily.

**Comment by nemith** [comment]
@pmazzini  and @yarikk  both come from the same development environment where master is where development happens.  I think we just need to define when a release is cut.  

Unless there is some big major changes we want to start working (like dev-2.x) where we want to collect a bunch of larger changes that are not compatible in some way.   Then again we can just do that on master and cut a 1.x branch for bug fixes instead.

**Comment by jeffbean** [comment]
this seems fine to me. Internally I have now cut and test the 1.0.2 release, from here I am open to any process, as long as we are consistant :D.

**Pull request closed without merging**
